### ISSUE TITLE
count parameter in get_timeseries()

### ISSUE THREAD

**Issue by guynamedjohn** [ahmedmohamedali/eikonapir#10]
The count parameter doesn't seem to work (or maybe I'm doing something wrong). 

It seems to default 3000. If I try to increase or decrease the number. E.g., if I increase to 6000, still get 3000. If I decrease to 100, still get 3000 (or the maximum available). 

Also, I need to do a as.integer() on any number submitted or I get an error saying it isn't an integer (which might be true but most functions of this type don't have this requirement).

**Comment by hoenie-ams** [comment]
FYI: 3000 is currently the maximum....
