### ISSUE TITLE
errors with eikonapir queries

### ISSUE THREAD

**Issue by casras111** [ahmedmohamedali/eikonapir#12]
There seems to be a change in the Eikon interface that breaks previously running script running with eikonapir. Wanted you to be aware of the following thread in the developers forum https://community.developers.thomsonreuters.com/questions/28988/eikon-api-errors-in-previously-working-scripts.html.

In addition when running the get_symbology command with debug on there's a strange message about the app id, seems like it's "forgetting" the app id that was set just earlier:

> eikonapir::set_app_id("7ed51e7f947b428f9690bac0c1116b122cac54a5")
> get_symbology("MSFT.O","RIC","ISIN",raw_ouput = FALSE,debug = TRUE)
[1] "Request *************************************"
{"Entity":{"E":["SymbologySearch"],"W":{"symbols":[["MSFT.O"]],"from":["RIC"],"to":[["ISIN"]],"bestMatchOnly":[true]}}} 
[1] "Response *************************************"
[1] "{\"ErrorCode\":1401,\"ErrorMessage\":\"Application id ED142B67FBF0B94BAC3AB is invalid\"}"
[1] "Response status *************************************"
[1] 403
Error in print.default("HTTP Error, code= ", response$status_code, sep = "") : 
  invalid 'digits' argument

**Comment by hoenie-ams** [comment]
Does this solve the issue @casras111? Thanks for confirming!

**Comment by casras111** [comment]
The new version fixes the get_symbology issue and my tests work in my environment. Thanks a lot. @hoenie-ams @ahmedmohamedali
