### ISSUE TITLE
get_timeseries - "corax " is not Working.

### ISSUE THREAD

**Issue by PedroAMBH** [ahmedmohamedali/eikonapir#14]
Hi, 
I try to get an adjusted price and it didn't work.

corax parameter for the get_timeseries is not working.
"Error in set_string_property(payload, "corax", corax) : 
  object 'payload' not found"

Good job with the library!

**Comment by hoenie-ams** [comment]
@PedroAMBH, this is a known issue and has been reported to development (see the [Developer Portal](https://community.developers.thomsonreuters.com/questions/15496/get-timeseries-corax-parameter-not-working.html)). It is not a issue in this wrapper.
