### ISSUE TITLE
Failed to connect to localhost port 9000:

### ISSUE THREAD

**Issue by gbrmartinelli** [ahmedmohamedali/eikonapir#17]
Hi, when i run the command get_timeseries (or any other command) I get: 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to localhost port 9000: Connection refused

The package used to work until some tiime ago, and I tried everything (reinstalling and more), but this did not solve the issue. Can you please let me know if you know a solution? thanks!

**Comment by gbrmartinelli** [comment]
Actually now i am getting a different error, which is

df = get_timeseries(list("MSFT.O","VOD.L","IBM.N"),list("*"),"2016-01-01T15:04:05","2016-01-10T15:04:05","daily")
Error in print.default("HTTP Error, code= ", response$status_code, sep = "") : 
  invalid 'digits' argument

do you know where this can come from?

**Comment by ahmedmohamedali** [comment]
@gbrmartinelli, @jfrank-summit,

Please make sure your are setting the correct application key
set_app_id('<XXXX>')

**Comment by RicoDiel** [comment]
Another potential problem might be, that you are currently not logged in into Eikon.
I also had this problem, but starting Eikon on the PC fixed it.

**Comment by benyizhang** [comment]
I have the same issue here. I am pretty certain that I have logged into the Eikon. But I still have this issues again.
