### ISSUE TITLE
Problem by retrieving tick data

### ISSUE THREAD

**Issue by DortheB** [ahmedmohamedali/eikonapir#5]
I have a problem by obtaining tick data from EIKON.  I can get the data, when I use "minut" (or "daily"  or "hour") , but not when I use "tick". I cannot figure out why. 

Code:
eikonapir.set_app_id('YOUR_APP_ID')

%# This works fine (minut data)
df = get_timeseries('IBM','*',start_date = '2017-03-21T00:00:00Z',end_date='2017-03-21T16:00:00Z',interval='minute')

%# This does NOT work (tick data)
df = get_timeseries('IBM','*',start_date = '2017-03-21T00:00:00Z',end_date='2017-03-21T16:00:00Z',interval='tick')

Thanks in advance - and thank you very much for a very useable package!

**Comment by hoenie-ams** [comment]
@DortheB , you are reaching the 90 day cap for tick history, that's why it won't work. An error message should be helpful here.
