### ISSUE TITLE
Port number has changed

### ISSUE THREAD

**Issue by hoenie-ams** [ahmedmohamedali/eikonapir#8]
Hi @ahmedmohamedali, recently the API capabilities have been integrated into the Eikon Toolbar. The port number being used now is 9000 (instead of 36036). Could you please amend this in the source code? The package is still looking for 36036, so we get the following error:
`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server`
Thanks!

**Comment by ahmedmohamedali** [comment]
The default port is now changed to 9000. The helper API function set_proxy_port was also added to change the port value grammatically.
Usage example: 
`set_proxy_port(36036)`
