### ISSUE TITLE
proxy error after downloading latest version of package

### ISSUE THREAD

**Issue by casras111** [ahmedmohamedali/eikonapir#9]
I did an install of latest package from github hoping that by getting the version with the new port number to Eikon I'll be able to work without relogging every time I move from Eikon to R. Now I can't get any data, not when I'm logged in Eikon and not when I log in the separate Eikon API proxy. The error message is:

Error in get_proxy_port() : 
  no slot of name "proxy_port" for this object of class "RequestInfo"

Thanks, claudiu

**Comment by casras111** [comment]
A workaround I found to work after looking at the changes in github is to add the line below after setting the app_id.

set_proxy_port(9000L)

**Comment by qweez** [comment]
Since the Mac Version is still using the old Port, it looks like the the Port has to stay at the default port 36036. Otherwise the connection is refused. 

Therefore for any Mac users:
set_proxy_port(36036L)

Best

**Comment by ahmedmohamedali** [comment]
Closing this issue as @qweez  workaround works.
